[workspace]
resolver = "3"
members = ["api", "app", "cli", "core", "monitor"]

[workspace.package]
version = "0.0.0-alpha.4"
edition = "2024"
authors = ["Javier E. <jaedns@gmail.com>"]
homepage = "https://id.mango3.app"
repository = "https://github.com/mangocubed/identity"

[workspace.dependencies]
apalis = "0.7.4"
apalis-redis = "0.7.4"
axum = "0.8.8"
chrono = { version = "0.4.42", features = ["serde"] }
rust_iso3166 = "0.1.14"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlx = "0.8.6"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.19.0", features = ["serde"] }
identity-core = { path = "core" }
sdk = { git = "https://github.com/mangocubed/sdk.git", tag = "v0.0.0-alpha.23" }

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
incremental = false
