[package]
name = "identity-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.52", features = ["derive"] }
tokio = { workspace = true }
uuid = { workspace = true }
identity-core = { workspace = true }
