[package]
name = "identity-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[build-dependencies]
sdk = { workspace = true, features = ["build"] }
chrono = "0.4.42"

[dependencies]
axum = { workspace = true, optional = true }
chrono = { workspace = true }
dioxus = { version = "0.7.2", features = ["fullstack", "router"] }
headers = { version = "0.4.1", optional = true }
http = "1.4.0"
rust_iso3166 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, optional = true }
url = "2.5.8"
uuid = { workspace = true }
identity-core = { workspace = true, optional = true }
sdk = { workspace = true, features = ["app"] }

[features]
default = ["web"]
web = ["dioxus/web", "sdk/web"]
server = [
    "dep:axum",
    "dep:headers",
    "dep:tokio",
    "dep:identity-core",
    "dioxus/server",
    "sdk/server",
]
